apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:  
  executor: |
    imagePullPolicy: Always
    resources:
      requests:
        cpu: 200m
        memory: 128Mi

  artifactRepository: |
    archiveLogs: true
    s3:
      endpoint: s3.amazonaws.com
      bucket: <bucket-name>
      region: us-east-1
      insecure: false
      keyFormat: "my-artifacts\
        /{{workflow.creationTimestamp.Y}}\
        /{{workflow.creationTimestamp.m}}\
        /{{workflow.creationTimestamp.d}}\
        /{{workflow.name}}\
        /{{pod.name}}"
      useSDKCreds: true
      encryptionOptions:
        enableEncryption: false
