apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-example-
  namespace: argo
spec:
  entrypoint: main
  podGC:
    strategy: OnPodSuccess
  ttlStrategy:
    secondsAfterCompletion: 20
  templates:
  - name: main
    dag:
      tasks:
      - name: main
        template: hello
        withSequence:
          count: 170
  - name: hello
    resource:
      action: create
      setOwnerReference: true
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: hello-world-
          namespace: argo
        spec:
          entrypoint: whalesay
          podGC:
            strategy: OnPodSuccess
          ttlStrategy:
            secondsAfterCompletion: 20
          templates:
          - name: whalesay
            container:
              # This docker container works on both ARM and x64
              image: ghcr.io/tico24/whalesay
              command: [cowsay]
              args: ["Hello ArgoCon!"]
      successCondition: status.phase == Succeeded
      failureCondition: status.phase in (Failed, Error)
